<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenceRepository extends EntityRepository
{
    public function search($data, $page = 0, $max = NULL, $getResult = true)
    {
        $qb = $this->_em->createQueryBuilder();
        $query = isset($data['query']) && $data['query']?$data['query']:null;
        $qb->select('m')
            ->from('AppBundle:Agence', 'm')
        ;
        if ($query) {
            $qb->andWhere('m.nom like :query OR m.reseau like :query OR m.adresse like :query OR m.adresse2 like :query OR m.cp like :query OR m.ville like :query OR m.email like :query OR m.tel like :query OR m.fax like :query OR m.web like :query ')
                ->setParameter('query', "%".$query."%");
        }
        if ($max) {
            $preparedQuery = $qb->getQuery()
                ->setMaxResults($max)
                ->setFirstResult($page * $max)
            ;
        } else {
            $preparedQuery = $qb->getQuery();
        }
        return $getResult?$preparedQuery->getResult():$preparedQuery;
    }
}
