<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * B2BInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class B2BInvoiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getInvoicePartnerAgencyB2B($year, $month){

        $qb = $this->createQueryBuilder('b')
            ->select("b , sum(b.totalPerson) as totalPerson, sum(b.price) as price_b2b, sum(b.netPrice) as netPrice_b2b")
            ->where('b.year = :year ')
            ->andWhere('b.month = :month')
            ->andWhere('b.monthlyB2bEnvoice is null')
            ->setParameter('year', $year)
            ->setParameter('month', $month)
            ->groupBy('b.partnerAgency')
            ->getQuery();

        return  $qb->getResult();
    }

    public function getAllInvoicePartnerAgencyB2B($year, $month, $partenrAgency = null){

        $qb = $this->createQueryBuilder('b')
            ->where('b.year = :year ')
            ->andWhere('b.month = :month')
            ->andWhere('b.monthlyB2bEnvoice is null');
        if($partenrAgency){
            $qb->andWhere('b.partnerAgency = :partenrAgency')
                ->setParameter('partenrAgency', $partenrAgency);
        }
        $qb->setParameter('year', $year)
            ->setParameter('month', $month)
            ->orderBy('b.createdAt', 'DESC')
        ;

        return  $qb->getQuery()->getResult();
    }
}
