<?php

namespace AppBundle\Repository;

/**
 * BalanceHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BalanceHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
