<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{


  public function getActivatedCity()
  {
    $qb = $this->createQueryBuilder('g')
                ->where("g.status = 'active'");

            return $qb;

  }


}
