<?php

namespace AppBundle\Repository;

use AppBundle\Entity\InterVillePrices;
use AppBundle\Entity\Location;
use Doctrine\ORM\EntityRepository;

/**
 * InterVillePricesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterVillePricesRepository extends EntityRepository
{   use CountTrait;
    use ZipCodeTrait;

    public function getZipCodes($like = null){
        $qb = $this->createQueryBuilder('l')
            ->select('DISTINCT l.zipCode')
            ->where('l.zipCode != :gare_chalon ' )
            ->andWhere('l.zipCode != :gare_reims')
            ->setParameter('gare_reims',Location::GARE_REIMS)
            ->setParameter('gare_chalon',Location::GARE_CHALONS);

        if ($like){
            $qb = $qb->where('l.zipCode like :like ')
                ->setParameter('like',"%$like%");
        }

        return $qb->getQuery()->getScalarResult();
    }

    /**
     * @return InterVillePrices[]
     */
    public function getAvailableTownList(){
        $qb = $this->createQueryBuilder('l')
            ->select('l')
            ->where('l.zipCode != :gare_chalon ' )
            ->andWhere('l.zipCode != :gare_reims')
            ->setParameter('gare_reims',Location::GARE_REIMS)
            ->setParameter('gare_chalon',Location::GARE_CHALONS);
        return $qb->getQuery()->getResult();
    }

}
