<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MonthlyCommissionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MonthlyCommissionRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getLastMonthlyCommission()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT commission FROM AppBundle:MonthlyCommission commission ORDER BY commission.id DESC')
            ->getResult()[0];
    }
}
