<?php

namespace AppBundle\Repository;

/**
 * RelayCustomerDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelayCustomerDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
